version: 2.1
executors:
  node10:
    docker:
    - image: circleci/node:10-stretch
      environment:
        NPM_CONFIG_PREFIX: "~/.npm-global"
        working_directory: ~/repo

orbs:
  helix-post-deploy: adobe/helix-post-deploy@1.10.0
  puppeteer: threetreeslight/puppeteer@0.1.2

jobs:
  build:
    executor: node10
    steps:
      - checkout

      - run:
          name: install latest npm
          command: sudo npm -g install npm
      - run:
          name: Installing Dependencies
          command: npm install
      - run: mkdir junit
      - puppeteer/install
      - run:
          name: Test and Code Coverage
          command: npm run test
          environment:
            MOCHA_FILE: junit/test-results.xml
      - store_test_results:
          path: junit
      - store_artifacts:
          path: junit
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project

  operations:
    executor: node10
    steps:
      - attach_workspace:
          at: /home/circleci
      - helix-post-deploy/monitoring:
          newrelic_name: Adobe Blog - Uptime
          newrelic_url: https://blog.adobe.com
          newrelic_script: ./monitoring/api_test.js
          newrelic_group_policy: Customer Sites

      - helix-post-deploy/monitoring:
          newrelic_name: Adobe Blog - Content (cached)
          newrelic_url: https://blog.adobe.com
          newrelic_type: browser
          newrelic_script: ./monitoring/scripted_browser.js
          newrelic_group_policy: Customer Sites

      - helix-post-deploy/monitoring:
          newrelic_name: Adobe Blog - Content (uncached)
          newrelic_url: https://theblog-adobe.hlx.page
          newrelic_type: browser
          newrelic_script: ./monitoring/scripted_browser.js
          newrelic_group_policy: Customer Sites

      - helix-post-deploy/monitoring:
          newrelic_name: Adobe Blog - Homepage (cached)
          newrelic_script: ./monitoring/homepage_test.js
          newrelic_group_policy: Customer Sites
          newrelic_locations: AWS_US_WEST_1
          newrelic_frequency: 5

workflows:
  version: 2
  build:
    jobs:
      - build
      - operations:
          requires:
            - build
          context: Project Helix
          filters:
            branches:
              only: master
