version: 2.1
executors:
  node10:
    docker:
    - image: circleci/node:10-stretch
      environment:
        NPM_CONFIG_PREFIX: "~/.npm-global"
    working_directory: ~/repo

orbs:
  helix-post-deploy: adobe/helix-post-deploy@1.6.0

jobs:
  operations:
    executor: node10
    steps:
      - checkout
      - run:
          name: install npm 6.9.0
          command: sudo npm -g install npm@6.9.0
      - run:
          name: Installing Dependencies
          command: npm ci
      - helix-post-deploy/monitoring:
          newrelic_name: Adobe Blog - Uptime
          newrelic_url: https://theblog.helix-demo.xyz
          newrelic_script: ./monitoring/api_test.js
          newrelic_group_policy: Customer Sites

      - helix-post-deploy/monitoring:
          newrelic_name: Adobe Blog - Content (cached)
          newrelic_url: https://theblog.helix-demo.xyz
          newrelic_type: browser
          newrelic_script: ./monitoring/scripted_browser.js
          newrelic_group_policy: Customer Sites

      - helix-post-deploy/monitoring:
          newrelic_name: Adobe Blog - Content (uncached)
          newrelic_url: https://theblog-adobe.hlx.page
          newrelic_type: browser
          newrelic_script: ./monitoring/scripted_browser.js
          newrelic_group_policy: Customer Sites

workflows:
  version: 2
  build:
    jobs:
      - operations:
          context: Project Helix
          filters:
            branches:
              only: master
